import {
  Links,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
  useRouteError,
} from 'react-router';

import {
  Component,
  type ReactNode,
  useEffect,
  useState,
} from 'react';
import './global.css';

// @ts-expect-error -- virtual module generated by Vite plugin at build time
import { LoadFonts } from 'virtual:load-fonts.jsx';
// @ts-expect-error -- generated auth module, no type declarations available
import { SessionProvider } from '@auth/create/react';
import { Toaster } from 'sonner';

export const links = () => [
  { rel: "icon", type: "image/x-icon", href: "/favicon.ico?v=3" },
  { rel: "apple-touch-icon", sizes: "180x180", href: "/apple-touch-icon.png" },
  { rel: "icon", type: "image/png", sizes: "32x32", href: "/favicon-32x32.png" },
  { rel: "icon", type: "image/png", sizes: "16x16", href: "/favicon-16x16.png" },
  { rel: "manifest", href: "/site.webmanifest" },
];

const LoadFontsSSR = import.meta.env.SSR ? LoadFonts : null;
if (import.meta.hot) {
  import.meta.hot.on('update-font-links', (urls: string[]) => {
    for (const link of document.querySelectorAll('link[data-auto-font]')) {
      link.remove();
    }
    for (const url of urls) {
      const link = document.createElement('link');
      link.rel = 'stylesheet';
      link.href = url;
      link.dataset.autoFont = 'true';
      document.head.appendChild(link);
    }
  });
}

// ─── Beautiful Error Page ─────────────────────────────────────────────
function MDXErrorPage({ error }: { error: unknown }) {
  const [showDetails, setShowDetails] = useState(false);

  const errorMessage =
    error instanceof Error ? error.message : 'An unexpected error occurred';
  const errorStack =
    error instanceof Error ? error.stack : JSON.stringify(error, null, 2);

  return (
    <div
      style={{
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontFamily: "'Inter', 'Segoe UI', system-ui, sans-serif",
        background: '#f6f7fb',
        color: '#111827',
        padding: '24px',
        position: 'relative',
        overflow: 'hidden',
      }}
    >
      {/* Background glows */}
      <div
        style={{
          position: 'absolute',
          top: '-100px',
          left: '-100px',
          width: '400px',
          height: '400px',
          borderRadius: '50%',
          background: 'rgba(249, 115, 22, 0.1)',
          filter: 'blur(100px)',
          pointerEvents: 'none',
        }}
      />
      <div
        style={{
          position: 'absolute',
          bottom: '-100px',
          right: '-100px',
          width: '400px',
          height: '400px',
          borderRadius: '50%',
          background: 'rgba(249, 115, 22, 0.08)',
          filter: 'blur(100px)',
          pointerEvents: 'none',
        }}
      />

      <div
        style={{
          position: 'relative',
          maxWidth: '520px',
          width: '100%',
          textAlign: 'center',
        }}
      >
        {/* Error icon */}
        <div
          style={{
            width: '80px',
            height: '80px',
            borderRadius: '24px',
            background: 'linear-gradient(135deg, #ef4444, #dc2626)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto 24px',
            boxShadow: '0 8px 32px rgba(239, 68, 68, 0.3)',
          }}
        >
          <svg
            width="40"
            height="40"
            viewBox="0 0 24 24"
            fill="none"
            stroke="white"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <circle cx="12" cy="12" r="10" />
            <line x1="12" y1="8" x2="12" y2="12" />
            <line x1="12" y1="16" x2="12.01" y2="16" />
          </svg>
        </div>

        <h1
          style={{
            fontSize: '28px',
            fontWeight: 700,
            marginBottom: '8px',
            color: '#111827',
          }}
        >
          Something went wrong
        </h1>

        <p
          style={{
            color: '#6B7280',
            fontSize: '15px',
            marginBottom: '32px',
            lineHeight: 1.6,
          }}
        >
          {errorMessage}
        </p>

        {/* Action buttons */}
        <div
          style={{
            display: 'flex',
            gap: '12px',
            justifyContent: 'center',
            flexWrap: 'wrap',
            marginBottom: '24px',
          }}
        >
          <button
            onClick={() => (window.location.href = '/')}
            style={{
              background: 'linear-gradient(135deg, #F97316, #EA580C)',
              color: 'white',
              border: 'none',
              borderRadius: '14px',
              padding: '12px 28px',
              fontSize: '14px',
              fontWeight: 600,
              cursor: 'pointer',
              boxShadow: '0 4px 16px rgba(249, 115, 22, 0.3)',
              transition: 'transform 0.15s, box-shadow 0.15s',
            }}
            onMouseOver={(e) => {
              e.currentTarget.style.transform = 'translateY(-1px)';
              e.currentTarget.style.boxShadow = '0 6px 24px rgba(249, 115, 22, 0.4)';
            }}
            onMouseOut={(e) => {
              e.currentTarget.style.transform = 'translateY(0)';
              e.currentTarget.style.boxShadow = '0 4px 16px rgba(249, 115, 22, 0.3)';
            }}
          >
            Go Home
          </button>

          <button
            onClick={() => window.location.reload()}
            style={{
              background: '#ffffff',
              color: '#374151',
              border: '1px solid #e5e7eb',
              borderRadius: '14px',
              padding: '12px 28px',
              fontSize: '14px',
              fontWeight: 600,
              cursor: 'pointer',
              transition: 'background 0.15s',
            }}
            onMouseOver={(e) => {
              e.currentTarget.style.background = '#f3f4f6';
            }}
            onMouseOut={(e) => {
              e.currentTarget.style.background = '#ffffff';
            }}
          >
            Retry
          </button>
        </div>

        {/* Expandable error details */}
        <button
          onClick={() => setShowDetails(!showDetails)}
          style={{
            background: 'none',
            border: 'none',
            color: '#9CA3AF',
            fontSize: '12px',
            cursor: 'pointer',
            padding: '4px 8px',
          }}
        >
          {showDetails ? '▼ Hide details' : '▶ Show details'}
        </button>

        {showDetails && (
          <div
            style={{
              marginTop: '16px',
              background: '#ffffff',
              border: '1px solid #e5e7eb',
              borderRadius: '16px',
              padding: '16px',
              textAlign: 'left',
              maxHeight: '240px',
              overflowY: 'auto',
            }}
          >
            <pre
              style={{
                color: '#6B7280',
                fontSize: '11px',
                whiteSpace: 'pre-wrap',
                wordBreak: 'break-all',
                margin: 0,
                fontFamily: "'Fira Code', 'Cascadia Code', monospace",
              }}
            >
              {errorStack}
            </pre>
          </div>
        )}

        <p
          style={{
            color: '#D1D5DB',
            fontSize: '11px',
            marginTop: '32px',
          }}
        >
          MDX Billing · Premium Shop Management
        </p>
      </div>
    </div>
  );
}

// ─── Error Boundary (class component) ──────────────────────────────────
type ErrorBoundaryProps = { children: ReactNode };
type ErrorBoundaryState = { hasError: boolean; error: unknown | null };

class ErrorBoundaryWrapper extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  state: ErrorBoundaryState = { hasError: false, error: null };

  static getDerivedStateFromError(error: unknown): ErrorBoundaryState {
    return { hasError: true, error };
  }

  componentDidCatch(error: unknown, info: unknown) {
    console.error('[MDX Billing] Error caught:', error, info);
  }

  render() {
    if (this.state.hasError) {
      return <MDXErrorPage error={this.state.error} />;
    }
    return this.props.children;
  }
}

// ─── Client-only wrapper ───────────────────────────────────────────────
function LoaderWrapper({ loader }: { loader: () => React.ReactNode }) {
  return <>{loader()}</>;
}

export const ClientOnly: React.FC<{ loader: () => React.ReactNode }> = ({ loader }) => {
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  return (
    <ErrorBoundaryWrapper>
      {isMounted ? <LoaderWrapper loader={loader} /> : null}
    </ErrorBoundaryWrapper>
  );
};

// ─── Root Layout ───────────────────────────────────────────────────────
export function Layout({ children }: { children: ReactNode }) {
  const isMobile = typeof window !== 'undefined' ? window.innerWidth < 768 : false;
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>MDX Billing — Premium Shop App</title>
        <meta name="description" content="Manage products, billing, sales, customers and analytics — all in one place. Fast, secure and built for your business." />
        <meta property="og:title" content="MDX Billing — Premium Shop App" />
        <meta property="og:description" content="Manage products, billing, sales, customers and analytics — all in one place. Fast, secure and built for your business." />
        <meta property="og:image" content="https://mdx-billing.app/preview.png" />
        <meta property="og:image:width" content="1600" />
        <meta property="og:image:height" content="900" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="MDX Billing — Premium Shop App" />
        <meta name="twitter:description" content="Manage products, billing, sales, customers and analytics — all in one place. Fast, secure and built for your business." />
        <meta name="twitter:image" content="https://mdx-billing.app/preview.png" />
        <Meta />
        <Links />
        {LoadFontsSSR ? <LoadFontsSSR /> : null}
      </head>
      <body>
        <ClientOnly loader={() => children} />
        <Toaster position={isMobile ? 'top-center' : 'bottom-right'} />
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

// ─── Route-level Error Boundary ────────────────────────────────────────
export function ErrorBoundary() {
  const error = useRouteError();
  return <MDXErrorPage error={error} />;
}

// ─── App ───────────────────────────────────────────────────────────────
export default function App() {
  return (
    <SessionProvider>
      <Outlet />
    </SessionProvider>
  );
}
